apiVersion: v1
kind: Service
metadata:
  name: carts
spec:
  selector:
    app: carts
    tier: backend
  ports:
  - name: "carts"
    protocol: TCP
    port: 5002
    targetPort: 5002
status:
  loadBalancer: {}