
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
    tier: frontend
  ports:
  - name: "client"
    protocol: TCP
    port: 80
    targetPort: 80
status:
  loadBalancer: {}