apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  selector:
    app: inventory
    tier: backend
  ports:
  - name: "inventory"
    protocol: TCP
    port: 5000
    targetPort: 5000
status:
  loadBalancer: {}