apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: orders
        tier: backend
    spec:
      containers:
      - env:
        image: dethbug/microservice-shop-orders:latest
        name: orders
        ports:
        - containerPort: 5001
        resources: {}
      restartPolicy: Always
status: {}